# This workflow will install Python dependencies and run tests

name: Run tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./src/tests/requirements.txt -r ./src/controller/requirements.txt -r ./src/common/requirements.txt
    - name: Test with pytest
      run: |
        pytest ./src/tests
